"""!
Project Euler
James Munns
"""

import sys, time

#=====================================================================
def prjEuler():
    """!
    James Munns
    July 30th, 2012
    Project Euler #2:
        Each new term in the Fibonacci sequence is generated by adding
        the previous two terms. By starting with 1 and 2, the first 10
        terms will be:
            1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

        By considering the terms in the Fibonacci sequence whose values
        do not exceed four million, find the sum of the even-valued terms.
    Submitted 7/30/2012 - Pass
    """
    #Constants
    MAX_VAL = 4000000
    
    #Initalized variables
    last_val = 1
    current_val = 1
    sum = 0
    
    #Loop until reaching the maximum value
    while( current_val < MAX_VAL ):
    
        #If even, add to total sum
        if( not ( current_val % 2 ) ):
            sum += current_val
        
        #Increment values
        temp_val = last_val + current_val
        last_val = current_val
        current_val = temp_val
        
    print "The sum is %d" % sum
    return

#=====================================================================
def main():
    time_start = time.clock()
    prjEuler()
    print "Time taken: %.2fms" % ((time.clock() - time_start) * 1000)
    return 0

#=====================================================================
if( __name__ == "__main__" ):
    sys.exit( main() )